<a href="https://colab.research.google.com/github/hamednasr/TensorFlow-Projects/blob/main/Analyzing_Tweets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting Tweet`s Overal Message:
## This is a kaggle competition.
https://www.kaggle.com/competitions/nlp-getting-started/data

In [1]:
import tensorflow as tf
import pandas as pd
import random
from sklearn.model_selection import train_test_split

In [2]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2022-08-31 19:26:50--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2022-08-31 19:26:50 (21.7 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [3]:
from helper_functions import unzip_data, plot_loss_curves, compare_historys

In [4]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2022-08-31 19:26:50--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.214.128, 173.194.215.128, 173.194.216.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.214.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.006s  

2022-08-31 19:26:50 (91.6 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [5]:
unzip_data('/content/nlp_getting_started.zip')

## Data Exploration:

In [6]:
train_data = pd.read_csv('train.csv')
train_data

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [7]:
train_data['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [8]:
test_data = pd.read_csv('test.csv')
test_data

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

In [9]:
random_data = train_data.sample(frac=0.0006)
for i in range(len(random_data)):
  print(f'tweet number {i+1} :')
  if random_data.iloc[i, 4]==1:
    target = 'a Disaster'
  else:
    target = 'NOT Disaster'
  print(f'{random_data.iloc[i, 3]} : This is {target} tweet')
  print('------------------------------------\n')


tweet number 1 :
@King_Naruto_ As long as I see Madara bleeding I'm good ?? : This is NOT Disaster tweet
------------------------------------

tweet number 2 :
China's Stock Market Crash: Are There Gems In The Rubble?: China‰Ûªs stock market crash this summer has sparked ... http://t.co/2OqSGZqlbz : This is NOT Disaster tweet
------------------------------------

tweet number 3 :
Dan Hughes was taken off on a stretcher after Danielle Robinson collided @OU_WBBall hope they are both ok he called SOME  games over years : This is NOT Disaster tweet
------------------------------------

tweet number 4 :
Christian Attacked by Muslims at the Temple Mount after Waving Israeli Flag via Pamela Geller - ... http://t.co/1pDJoq4Jc1 : This is a Disaster tweet
------------------------------------

tweet number 5 :
the pastor was not in the scene of the accident......who was the owner of the range rover ? : This is a Disaster tweet
------------------------------------



## Extract validation data from train data:

In [10]:
train_data['text'].to_numpy()

array(['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all',
       'Forest fire near La Ronge Sask. Canada',
       "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected",
       ...,
       'M1.94 [01:04 UTC]?5km S of Volcano Hawaii. http://t.co/zDtoyd8EbJ',
       'Police investigating after an e-bike collided with a car in Little Portugal. E-bike rider suffered serious non-life threatening injuries.',
       'The Latest: More Homes Razed by Northern California Wildfire - ABC News http://t.co/YmY4rSkQ3d'],
      dtype=object)

In [11]:
train_data['target'].to_numpy()

array([1, 1, 1, ..., 1, 1, 1])

In [12]:
train_data, val_data, train_label, val_label = train_test_split(train_data['text'].to_numpy(), train_data['target'].to_numpy(), 
                                                                test_size=0.1, 
                                                                random_state=42)

In [13]:
val_data[:10], val_label[:10]

(array(['So you have a new weapon that can cause un-imaginable destruction.',
        'The f$&amp;@ing things I do for #GISHWHES Just got soaked in a deluge going for pads and tampons. Thx @mishacollins @/@',
        'DT @georgegalloway: RT @Galloway4Mayor: \x89ÛÏThe CoL police can catch a pickpocket in Liverpool Stree... http://t.co/vXIn1gOq4Q',
        'Aftershock back to school kick off was great. I want to thank everyone for making it possible. What a great night.',
        'in response to trauma Children of Addicts develop a defensive self - one that decreases vulnerability. (3',
        '@Calum5SOS you look like you got caught in a rainstorm this is amazing and disgusting at the same time',
        'my favorite lady came to our volunteer meeting\nhopefully joining her youth collision and i am excite http://t.co/Ij0wQ490cS',
        '@brianroemmele UX fail of EMV - people want to insert and remove quickly like a gas pump stripe reader. 1 person told me it crashed the POS',
       

## Tokenization (Vectorization):

In [14]:
sum([len(tweet.split()) for tweet in train_data])

101905

In [15]:
round(sum([len(tweet.split()) for tweet in train_data])/len(train_data))

15

In [16]:
text_vectorizer = tf.keras.layers.TextVectorization(max_tokens=10000,
                                                       output_mode='int', 
                                                       output_sequence_length=15)

In [17]:
text_vectorizer.adapt(train_data)

In [18]:
sample_tweet = 'my name is hamed i am happy to meet you!'
text_vectorizer(sample_tweet)

<tf.Tensor: shape=(15,), dtype=int64, numpy=
array([  13,  707,    9,    1,    8,  171,  714,    5, 1815,   12,    0,
          0,    0,    0,    0])>

In [19]:
random_tweet = random.choice(train_data)
print('tweet: ', random_tweet,'\n\n')
print('vectorized tweet: ', text_vectorizer(random_tweet))

tweet:  @tackettdc Like a scene from When Worlds Collide ...... 


vectorized tweet:  tf.Tensor(
[7814   25    3 1255   20   45 1226  491    0    0    0    0    0    0
    0], shape=(15,), dtype=int64)


In [20]:
#unique words
unique_words = text_vectorizer.get_vocabulary()
print(len(unique_words))
print(unique_words[:10])
print(unique_words[-10:])

10000
['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is']
['palm', 'palinfoen', 'palestinian\x89Û', 'palermo', 'pale', 'pakthey', 'pakistan\x89Ûªs', 'pakistans', 'pajamas', 'paints']


## Embedding:

In [21]:
embedding = tf.keras.layers.Embedding(input_dim = 10000, output_dim =32, input_length=None)

In [22]:
sample_embed = embedding(text_vectorizer(random_tweet))
sample_embed

<tf.Tensor: shape=(15, 32), dtype=float32, numpy=
array([[-0.02706599, -0.01248138, -0.01012506, -0.02122561,  0.04682242,
        -0.043373  , -0.02637695, -0.02893916, -0.00020723, -0.00846604,
        -0.0487288 , -0.02311137, -0.04277016,  0.04717236, -0.04847531,
        -0.03394391,  0.02907555, -0.03629314, -0.03272368, -0.01567413,
         0.03510605,  0.02078679,  0.0350765 ,  0.04235721, -0.04259734,
         0.01390686, -0.00071106,  0.01629099, -0.01734848,  0.02080298,
        -0.02112073,  0.02089203],
       [-0.01011775, -0.03396906,  0.00859766,  0.00644317,  0.03394867,
        -0.00529301,  0.03491023, -0.03692527, -0.02449355,  0.01719079,
         0.01028113,  0.03341886,  0.04943384, -0.00517983,  0.00506211,
         0.02312387, -0.04238087,  0.01451981, -0.04019014,  0.04431531,
         0.02014411, -0.04266074, -0.00092176,  0.03153095,  0.02153898,
        -0.04084607, -0.03198379, -0.02291607, -0.0201622 ,  0.00241444,
         0.02841489, -0.04872377],
    

## Analyze with Naive Bayes using TF-IDF:

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

In [24]:
model_0 = Pipeline([
                    ('tfidf', TfidfVectorizer()),
                    ('clf', MultinomialNB())
])

model_0.fit(train_data,train_label)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [25]:
val_pred = model_0.predict(val_data)
val_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [26]:
val_label[:10]

array([1, 0, 1, 0, 0, 0, 1, 1, 0, 1])

In [27]:
accuracy_score(val_label, val_pred)

0.7782152230971129

In [28]:
print(classification_report(val_label, val_pred))

              precision    recall  f1-score   support

           0       0.74      0.92      0.82       426
           1       0.86      0.60      0.70       336

    accuracy                           0.78       762
   macro avg       0.80      0.76      0.76       762
weighted avg       0.79      0.78      0.77       762



In [29]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [30]:
model_0.predict_proba(tweets)

array([[0.22063312, 0.77936688],
       [0.58453661, 0.41546339],
       [0.71572258, 0.28427742]])

In [31]:
model_0.predict(tweets)

array([1, 0, 0])

## Analyze with Vanilla Neural Network:

In [32]:
from helper_functions import create_tensorboard_callback

In [33]:
inputs = tf.keras.layers.Input(shape= (1,), dtype = tf.string)

x = text_vectorizer(inputs)

x = embedding(x)

# x = tf.transpose(x , perm = [0,2,1])

# print(x.shape)

x = tf.keras.layers.GlobalAveragePooling1D()(x)

x = tf.keras.layers.Dense(10, activation='relu')(x)

outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_1 = tf.keras.Model(inputs,outputs, name='ANN')

In [34]:
model_1.summary()

Model: "ANN"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 15, 32)            320000    
                                                                 
 global_average_pooling1d (G  (None, 32)               0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 10)                330       
                                                                 
 dense_1 (Dense)             (None, 1)                 11      

In [35]:
model_1.compile(loss = tf.keras.losses.BinaryCrossentropy(),
                 optimizer = tf.keras.optimizers.Adam(),
                 metrics= ['accuracy'])

In [36]:
train_label.shape

(6851,)

In [37]:
train_data.shape

(6851,)

In [38]:
# !rm -rf './tensorboard/ANN'

In [39]:
history_1 = model_1.fit(train_data, 
            train_label, 
            validation_data = (val_data,val_label), 
            epochs=10, 
            callbacks=[create_tensorboard_callback('tensorboard','ANN')])

Saving TensorBoard log files to: tensorboard/ANN/20220831-192653
Epoch 1/10
215/215 [==============================] - 3s 9ms/step - loss: 0.6259 - accuracy: 0.6879 - val_loss: 0.5363 - val_accuracy: 0.7651
Epoch 2/10
215/215 [==============================] - 2s 8ms/step - loss: 0.4238 - accuracy: 0.8260 - val_loss: 0.4805 - val_accuracy: 0.7940
Epoch 3/10
215/215 [==============================] - 2s 7ms/step - loss: 0.3115 - accuracy: 0.8748 - val_loss: 0.4865 - val_accuracy: 0.7835
Epoch 4/10
215/215 [==============================] - 2s 8ms/step - loss: 0.2423 - accuracy: 0.9101 - val_loss: 0.5266 - val_accuracy: 0.7782
Epoch 5/10
215/215 [==============================] - 2s 7ms/step - loss: 0.1917 - accuracy: 0.9292 - val_loss: 0.5593 - val_accuracy: 0.7769
Epoch 6/10
215/215 [==============================] - 2s 7ms/step - loss: 0.1531 - accuracy: 0.9472 - val_loss: 0.6118 - val_accuracy: 0.7638
Epoch 7/10
215/215 [==============================] - 2s 7ms/step - loss: 0.1260 - 

In [40]:
model_1.evaluate(val_data,val_label)

24/24 [==============================] - 0s 3ms/step - loss: 0.8235 - accuracy: 0.7402


[0.8235107064247131, 0.7401574850082397]

In [41]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [42]:
model_1.predict(tweets)

array([[0.9784072 ],
       [0.7917726 ],
       [0.08460793]], dtype=float32)

## Retrieve the trained word embeddings:

In [43]:
weights = model_1.get_layer('embedding').get_weights()[0]
weights

array([[ 0.25929037, -0.06279013, -0.06148194, ...,  0.14954968,
         0.10060261,  0.0653062 ],
       [ 0.24403132, -0.03507703, -0.0686942 , ...,  0.12375301,
         0.10604884,  0.02397103],
       [ 0.26330766, -0.00792165,  0.00596493, ...,  0.15860574,
         0.17530532,  0.0099184 ],
       ...,
       [ 0.08522397,  0.05309212,  0.0784494 , ...,  0.00166323,
        -0.00641821, -0.00086374],
       [ 0.01429316,  0.00259889, -0.01726699, ..., -0.02082995,
        -0.01213987, -0.01905471],
       [ 0.04047877, -0.02340493, -0.01548165, ...,  0.00393052,
         0.012569  , -0.03269402]], dtype=float32)

In [44]:
weights.shape

(10000, 32)

In [45]:
vocab = text_vectorizer.get_vocabulary()
vocab[:10]

['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is']

In [46]:
import io
out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(vocab):
  if index == 0:
    continue  # skip 0, it's padding.
  vec = weights[index]
  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()

In [47]:
# try:
#   from google.colab import files
#   files.download('vectors.tsv')
#   files.download('metadata.tsv')
# except Exception:
#   pass

Then, use [Embedding Projector](http://projector.tensorflow.org/) to Visualize the embeddings

## Analyze with LSTM model:

In [48]:
inputs = tf.keras.layers.Input(shape= (1), dtype = tf.string)

x = text_vectorizer(inputs)

x = embedding(x)

x = tf.keras.layers.LSTM(64,  return_sequences=True)(x)
x = tf.keras.layers.LSTM(32)(x)

x = tf.keras.layers.Dense(16, activation='relu')(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_2 = tf.keras.Model(inputs,outputs, name='LSTM')

In [49]:
model_2.summary()

Model: "LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 15, 32)            320000    
                                                                 
 lstm (LSTM)                 (None, 15, 64)            24832     
                                                                 
 lstm_1 (LSTM)               (None, 32)                12416     
                                                                 
 dense_2 (Dense)             (None, 16)                528       
                                                              

In [50]:
model_2.compile(loss = tf.keras.losses.BinaryCrossentropy(),
                 optimizer = tf.keras.optimizers.Adam(),
                 metrics= ['accuracy'])

In [51]:
# !rm -rf './tensorboard/LSTM'

In [52]:
history_2 = model_2.fit(train_data, 
            train_label, 
            validation_data = (val_data,val_label), 
            epochs=10, 
            callbacks=[create_tensorboard_callback('tensorboard','LSTM')])

Saving TensorBoard log files to: tensorboard/LSTM/20220831-192716
Epoch 1/10
215/215 [==============================] - 11s 30ms/step - loss: 0.1997 - accuracy: 0.9218 - val_loss: 0.8313 - val_accuracy: 0.7507
Epoch 2/10
215/215 [==============================] - 6s 26ms/step - loss: 0.0811 - accuracy: 0.9685 - val_loss: 0.8949 - val_accuracy: 0.7388
Epoch 3/10
215/215 [==============================] - 5s 25ms/step - loss: 0.0639 - accuracy: 0.9749 - val_loss: 1.2104 - val_accuracy: 0.7441
Epoch 4/10
215/215 [==============================] - 6s 27ms/step - loss: 0.0608 - accuracy: 0.9737 - val_loss: 1.0866 - val_accuracy: 0.7178
Epoch 5/10
215/215 [==============================] - 6s 26ms/step - loss: 0.0509 - accuracy: 0.9772 - val_loss: 1.2095 - val_accuracy: 0.7362
Epoch 6/10
215/215 [==============================] - 5s 24ms/step - loss: 0.0468 - accuracy: 0.9793 - val_loss: 1.5439 - val_accuracy: 0.7362
Epoch 7/10
215/215 [==============================] - 5s 25ms/step - loss: 

In [53]:
model_2.evaluate(val_data,val_label)

24/24 [==============================] - 0s 7ms/step - loss: 1.8930 - accuracy: 0.7139


[1.8929849863052368, 0.7139107584953308]

### custom tweets:

In [54]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [55]:
model_2.predict(tweets)

array([[0.9999676 ],
       [0.9162924 ],
       [0.00160667]], dtype=float32)

## Analyze with GRU model:

In [56]:
inputs = tf.keras.layers.Input(shape= (1), dtype = tf.string)

x = text_vectorizer(inputs)

x = embedding(x)

x = tf.keras.layers.GRU(64,  return_sequences=True)(x)
x = tf.keras.layers.GRU(32)(x)

x = tf.keras.layers.Dense(16, activation='relu')(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_3 = tf.keras.Model(inputs,outputs, name='GRU')

In [57]:
model_3.summary()

Model: "GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 15, 32)            320000    
                                                                 
 gru (GRU)                   (None, 15, 64)            18816     
                                                                 
 gru_1 (GRU)                 (None, 32)                9408      
                                                                 
 dense_4 (Dense)             (None, 16)                528       
                                                               

In [58]:
model_3.compile(loss = tf.keras.losses.BinaryCrossentropy(),
                 optimizer = tf.keras.optimizers.Adam(),
                 metrics= ['accuracy'])

In [59]:
# !rm -rf './tensorboard/RNN'

In [60]:
history_3 = model_3.fit(train_data, 
            train_label, 
            validation_data = (val_data,val_label), 
            epochs=10, 
            callbacks=[create_tensorboard_callback('tensorboard','GRU')])

Saving TensorBoard log files to: tensorboard/GRU/20220831-192822
Epoch 1/10
215/215 [==============================] - 11s 29ms/step - loss: 0.1503 - accuracy: 0.9431 - val_loss: 0.9846 - val_accuracy: 0.7087
Epoch 2/10
215/215 [==============================] - 5s 24ms/step - loss: 0.0608 - accuracy: 0.9781 - val_loss: 0.8491 - val_accuracy: 0.7205
Epoch 3/10
215/215 [==============================] - 5s 25ms/step - loss: 0.0526 - accuracy: 0.9785 - val_loss: 1.0873 - val_accuracy: 0.7493
Epoch 4/10
215/215 [==============================] - 5s 24ms/step - loss: 0.0416 - accuracy: 0.9822 - val_loss: 1.8826 - val_accuracy: 0.7152
Epoch 5/10
215/215 [==============================] - 5s 25ms/step - loss: 0.0450 - accuracy: 0.9812 - val_loss: 1.4369 - val_accuracy: 0.7283
Epoch 6/10
215/215 [==============================] - 5s 25ms/step - loss: 0.0381 - accuracy: 0.9813 - val_loss: 1.6457 - val_accuracy: 0.7283
Epoch 7/10
215/215 [==============================] - 5s 25ms/step - loss: 0

In [61]:
model_3.evaluate(val_data,val_label)

24/24 [==============================] - 0s 6ms/step - loss: 1.9038 - accuracy: 0.7415


[1.903810977935791, 0.7414698004722595]

### custom tweets:

In [62]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [63]:
model_3.predict(tweets)

array([[9.9997842e-01],
       [9.9813539e-01],
       [7.9515576e-04]], dtype=float32)

## Analyzie with Bidirectional LSTM model:

In [64]:
inputs = tf.keras.layers.Input(shape= (1), dtype = tf.string)

x = text_vectorizer(inputs)

x = embedding(x)

x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64,  return_sequences=True))(x)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32))(x)


x = tf.keras.layers.Dense(16, activation='relu')(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_4 = tf.keras.Model(inputs,outputs, name='Bidirectional-LSTM')

In [65]:
model_4.summary()

Model: "Bidirectional-LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 15, 32)            320000    
                                                                 
 bidirectional (Bidirectiona  (None, 15, 128)          49664     
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 64)               41216     
 nal)                                                            
                                                

In [66]:
model_4.compile(loss = tf.keras.losses.BinaryCrossentropy(),
                 optimizer = tf.keras.optimizers.Adam(),
                 metrics= ['accuracy'])

In [67]:
# !rm -rf './tensorboard/RNN'

In [68]:
history_4 = model_4.fit(train_data, 
            train_label, 
            validation_data = (val_data,val_label), 
            epochs=10, 
            callbacks=[create_tensorboard_callback('tensorboard','Bidirectional-LSTM')])

Saving TensorBoard log files to: tensorboard/Bidirectional-LSTM/20220831-192923
Epoch 1/10
215/215 [==============================] - 18s 45ms/step - loss: 0.1011 - accuracy: 0.9629 - val_loss: 1.1875 - val_accuracy: 0.7454
Epoch 2/10
215/215 [==============================] - 8s 37ms/step - loss: 0.0400 - accuracy: 0.9818 - val_loss: 1.4493 - val_accuracy: 0.7205
Epoch 3/10
215/215 [==============================] - 8s 38ms/step - loss: 0.0398 - accuracy: 0.9803 - val_loss: 1.3763 - val_accuracy: 0.7467
Epoch 4/10
215/215 [==============================] - 8s 38ms/step - loss: 0.0375 - accuracy: 0.9809 - val_loss: 1.6042 - val_accuracy: 0.7441
Epoch 5/10
215/215 [==============================] - 9s 44ms/step - loss: 0.0369 - accuracy: 0.9813 - val_loss: 1.8181 - val_accuracy: 0.7310
Epoch 6/10
215/215 [==============================] - 8s 37ms/step - loss: 0.0357 - accuracy: 0.9822 - val_loss: 1.6126 - val_accuracy: 0.7441
Epoch 7/10
215/215 [==============================] - 8s 37ms

In [69]:
model_4.evaluate(val_data,val_label)

24/24 [==============================] - 0s 10ms/step - loss: 1.5350 - accuracy: 0.7349


[1.5350419282913208, 0.7349081635475159]

### custom tweets:

In [70]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [71]:
model_4.predict(tweets)

array([[7.7287161e-01],
       [4.7660515e-01],
       [7.0527196e-04]], dtype=float32)

## Analyze with Convolutional 1D model:

In [72]:
inputs = tf.keras.layers.Input(shape= (1), dtype = tf.string)

x = text_vectorizer(inputs)

x = embedding(x)

# x = tf.transpose(x , perm = [0,2,1])

# print(x.shape)

# x = tf.keras.layers.Flatten()(x)
print(x.shape)

x = tf.keras.layers.Conv1D(filters=64, kernel_size=3,padding= 'valid')(x)
print(x.shape)
x = tf.keras.layers.Conv1D(filters=128, kernel_size=3,padding= 'valid')(x)
print(x.shape)

x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(16, activation='relu')(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_5 = tf.keras.Model(inputs,outputs, name='Bidirectional-LSTM')

(None, 15, 32)
(None, 13, 64)
(None, 11, 128)


In [73]:
model_5.summary()

Model: "Bidirectional-LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 15)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 15, 32)            320000    
                                                                 
 conv1d (Conv1D)             (None, 13, 64)            6208      
                                                                 
 conv1d_1 (Conv1D)           (None, 11, 128)           24704     
                                                                 
 global_average_pooling1d_1   (None, 128)              0         
 (GlobalAveragePooling1D)                       

In [74]:
model_5.compile(loss = tf.keras.losses.BinaryCrossentropy(),
                 optimizer = tf.keras.optimizers.Adam(),
                 metrics= ['accuracy'])

In [75]:
# !rm -rf './tensorboard/RNN'

In [76]:
history_5 = model_5.fit(train_data, 
            train_label, 
            validation_data = (val_data,val_label), 
            epochs=10, 
            callbacks=[create_tensorboard_callback('tensorboard','Bidirectional-LSTM')])

Saving TensorBoard log files to: tensorboard/Bidirectional-LSTM/20220831-193057
Epoch 1/10
215/215 [==============================] - 3s 12ms/step - loss: 0.1365 - accuracy: 0.9499 - val_loss: 0.9928 - val_accuracy: 0.7349
Epoch 2/10
215/215 [==============================] - 2s 11ms/step - loss: 0.0646 - accuracy: 0.9740 - val_loss: 1.2160 - val_accuracy: 0.7192
Epoch 3/10
215/215 [==============================] - 2s 11ms/step - loss: 0.0466 - accuracy: 0.9774 - val_loss: 1.4520 - val_accuracy: 0.7362
Epoch 4/10
215/215 [==============================] - 2s 11ms/step - loss: 0.0400 - accuracy: 0.9804 - val_loss: 1.6313 - val_accuracy: 0.7362
Epoch 5/10
215/215 [==============================] - 2s 10ms/step - loss: 0.0388 - accuracy: 0.9812 - val_loss: 1.8688 - val_accuracy: 0.7231
Epoch 6/10
215/215 [==============================] - 2s 11ms/step - loss: 0.0356 - accuracy: 0.9799 - val_loss: 1.9609 - val_accuracy: 0.7244
Epoch 7/10
215/215 [==============================] - 2s 11ms/

In [77]:
model_5.evaluate(val_data,val_label)

24/24 [==============================] - 0s 3ms/step - loss: 2.6490 - accuracy: 0.7034


[2.6489670276641846, 0.7034120559692383]

### custom tweets:

In [78]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [79]:
model_5.predict(tweets)

array([[0.99974126],
       [0.9929791 ],
       [0.22827303]], dtype=float32)

## Analyze with Universal Sentence Encoder tensorflow hub:

In [80]:
import tensorflow_hub as hub

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
embed_sample = embed(["The quick brown fox jumps over the lazy dog.",
                      "I am a sentence for which I would like to get its embedding"])

print(embed_sample)

# The following are example embedding output of 512 dimensions per sentence
# Embedding for: The quick brown fox jumps over the lazy dog.
# [-0.03133016 -0.06338634 -0.01607501, ...]
# Embedding for: I am a sentence for which I would like to get its embedding.
# [0.05080863 -0.0165243   0.01573782, ...]


tf.Tensor(
[[-0.03133017 -0.06338634 -0.01607501 ... -0.03242778 -0.0457574
   0.05370456]
 [ 0.05080861 -0.01652434  0.01573779 ...  0.00976657  0.03170121
   0.01788118]], shape=(2, 512), dtype=float32)


In [81]:
embed(train_data)

<tf.Tensor: shape=(6851, 512), dtype=float32, numpy=
array([[ 0.01178656, -0.00748094,  0.00952065, ...,  0.04002216,
        -0.07293098,  0.01045   ],
       [ 0.08340861, -0.03587737,  0.01278975, ..., -0.00764408,
        -0.06952015, -0.08435119],
       [ 0.03161547,  0.01725737, -0.00808266, ..., -0.03697908,
         0.03299483, -0.04934364],
       ...,
       [-0.03393723, -0.06167451,  0.04978931, ..., -0.05219645,
        -0.05812604, -0.0630734 ],
       [ 0.0215332 ,  0.06060665, -0.07061633, ..., -0.04428503,
        -0.00652964, -0.00850323],
       [ 0.02649508, -0.05326023, -0.05051778, ..., -0.01227468,
         0.01156288, -0.00953933]], dtype=float32)>

In [82]:
encoder_layer = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4",
                               input_shape=[],
                               trainable=False,
                               dtype=tf.string,
                               name= 'USE')

In [83]:
model_6 = tf.keras.Sequential([
    encoder_layer,
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')],
    name = 'USE_pretrained_model'
)

In [84]:
model_6.summary()

Model: "USE_pretrained_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE (KerasLayer)            (None, 512)               256797824 
                                                                 
 dense_10 (Dense)            (None, 64)                32832     
                                                                 
 dense_11 (Dense)            (None, 32)                2080      
                                                                 
 dense_12 (Dense)            (None, 1)                 33        
                                                                 
Total params: 256,832,769
Trainable params: 34,945
Non-trainable params: 256,797,824
_________________________________________________________________


In [85]:
model_6.compile(loss = tf.keras.losses.BinaryCrossentropy(),
                 optimizer = tf.keras.optimizers.Adam(),
                 metrics= ['accuracy'])

In [86]:
# !rm -rf './tensorboard/RNN'

In [87]:
history_6 = model_6.fit(train_data, 
            train_label, 
            validation_data = (val_data,val_label), 
            epochs=10, 
            callbacks=[create_tensorboard_callback('tensorboard','USE_pretrained_model')])

Saving TensorBoard log files to: tensorboard/USE_pretrained_model/20220831-193202
Epoch 1/10
215/215 [==============================] - 7s 16ms/step - loss: 0.4908 - accuracy: 0.7723 - val_loss: 0.4170 - val_accuracy: 0.8189
Epoch 2/10
215/215 [==============================] - 4s 17ms/step - loss: 0.4066 - accuracy: 0.8229 - val_loss: 0.4053 - val_accuracy: 0.8176
Epoch 3/10
215/215 [==============================] - 3s 12ms/step - loss: 0.3838 - accuracy: 0.8355 - val_loss: 0.4001 - val_accuracy: 0.8176
Epoch 4/10
215/215 [==============================] - 3s 12ms/step - loss: 0.3628 - accuracy: 0.8441 - val_loss: 0.4013 - val_accuracy: 0.8163
Epoch 5/10
215/215 [==============================] - 3s 13ms/step - loss: 0.3424 - accuracy: 0.8556 - val_loss: 0.3971 - val_accuracy: 0.8228
Epoch 6/10
215/215 [==============================] - 3s 13ms/step - loss: 0.3134 - accuracy: 0.8720 - val_loss: 0.4126 - val_accuracy: 0.8228
Epoch 7/10
215/215 [==============================] - 3s 12m

In [88]:
model_6.evaluate(val_data,val_label)

24/24 [==============================] - 0s 10ms/step - loss: 0.4979 - accuracy: 0.8031


[0.4979403018951416, 0.8031495809555054]

### custom tweets:

In [89]:
tweets=['earthquake hit california minutes ago', 
        'my car on fire now', 
        'I need a blue car']

In [90]:
model_6.predict(tweets)

array([[0.9984745 ],
       [0.9650059 ],
       [0.00851494]], dtype=float32)

## Finding most wrong predicted tweets:

In [91]:
train_data

array(["'McFadden Reportedly to Test Hamstring Thursday' via @TeamStream http://t.co/jWq4KvJH2j",
       'w--=-=-=-[ NEMA warns Nigerians to prepare for drought http://t.co/5uoOPhSqU3',
       "When I was cooking earlier I got electrocuted some crucial ?????? now I'm psychic lol",
       ...,
       'Omron HEM-712C Automatic Blood Pressure Monitor STANDARD AND LARGE BP CUFFS http://t.co/gJBAInQWN9 http://t.co/jPhgpL1c5x',
       'Officials say a quarantine is in place at an Alabama home over a possible Ebola case after developing symptoms... http://t.co/rqKK15uhEY',
       'I moved to England five years ago today. What a whirlwind of time it has been! http://t.co/eaSlGeA1B7'],
      dtype=object)

In [92]:
train_label

array([0, 1, 0, ..., 0, 1, 1])

In [93]:
import numpy as np
pred_probs = np.squeeze(model_6.predict(train_data))
print(pred_probs)
pred_label = np.squeeze(np.round(pred_probs))
pred_label

[0.15293044 0.79391134 0.01531976 ... 0.01272947 0.9971067  0.89760965]


array([0., 1., 0., ..., 0., 1., 1.], dtype=float32)

In [94]:
import pandas as pd
comparison_table = pd.DataFrame({'tweets':train_data,
              'target': train_label,
              'pred': pred_label,
              'prob': pred_probs})

comparison_table

tweets  target  pred  \
0     'McFadden Reportedly to Test Hamstring Thursda...       0   0.0   
1     w--=-=-=-[ NEMA warns Nigerians to prepare for...       1   1.0   
2     When I was cooking earlier I got electrocuted ...       0   0.0   
3                  I'm On Fire.  http://t.co/WATsmxYTVa       0   0.0   
4     More than 40 families affected by the fatal ou...       1   1.0   
...                                                 ...     ...   ...   
6846  @Eganator2000 There aren't many Obliteration s...       0   0.0   
6847  just had a panic attack bc I don't have enough...       0   0.0   
6848  Omron HEM-712C Automatic Blood Pressure Monito...       0   0.0   
6849  Officials say a quarantine is in place at an A...       1   1.0   
6850  I moved to England five years ago today. What ...       1   1.0   

          prob  
0     0.152930  
1     0.793911  
2     0.015320  
3     0.102810  
4     0.953237  
...        ...  
6846  0.303111  
6847  0.012939  
6848  0.012729  
6849  0.997107  
6850  0.897610  

[6851 rows x 4 columns]

In [95]:
worst_preds = comparison_table[comparison_table['target'] != comparison_table['pred']].sort_values('prob')
worst_preds

tweets  target  pred  \
4418  The media needs to stop publicizing mass murde...       1   0.0   
1507  OH MY GOD RYANS IN TROUBLE http://t.co/ADIp0UnXHU       1   0.0   
231   Omg if Cain dies i will be an emotional wreck ...       1   0.0   
2189  ‰ÛÏ@LordBrathwaite: Everyone Here: Ahh I hate ...       1   0.0   
3040  #Nursing alert: Emergency Department Psychiatr...       1   0.0   
...                                                 ...     ...   ...   
243   @adorableappple No reported flooding po in the...       0   1.0   
5890  Teen Disaster Preparedness Event in Van Nuys A...       0   1.0   
4648  wowo--=== 12000 Nigerian refugees repatriated ...       0   1.0   
4653  #hot  C-130 specially modified to land in a st...       0   1.0   
5582  Kosciusko police investigating pedestrian fata...       0   1.0   

          prob  
4418  0.005087  
1507  0.009996  
231   0.023653  
2189  0.030777  
3040  0.031587  
...        ...  
243   0.803092  
5890  0.821565  
4648  0.827007  
4653  0.938754  
5582  0.994299  

[342 rows x 4 columns]

In [96]:
worst_preds[:10]

tweets  target  pred  \
4418  The media needs to stop publicizing mass murde...       1   0.0   
1507  OH MY GOD RYANS IN TROUBLE http://t.co/ADIp0UnXHU       1   0.0   
231   Omg if Cain dies i will be an emotional wreck ...       1   0.0   
2189  ‰ÛÏ@LordBrathwaite: Everyone Here: Ahh I hate ...       1   0.0   
3040  #Nursing alert: Emergency Department Psychiatr...       1   0.0   
2320  Why are you deluged with low self-image? Take ...       1   0.0   
2360  Detonation fashionable mountaineering electron...       1   0.0   
3845  Reddit Will Now Quarantine‰Û_ http://t.co/pkUA...       1   0.0   
523   Do you feel like you are sinking in low self-i...       1   0.0   
5014  ?? New Ladies Shoulder Tote #Handbag Faux Leat...       1   0.0   

          prob  
4418  0.005087  
1507  0.009996  
231   0.023653  
2189  0.030777  
3040  0.031587  
2320  0.031758  
2360  0.032980  
3845  0.037642  
523   0.041536  
5014  0.041920

In [97]:
worst_preds[-10:]

tweets  target  pred  \
4517  Hollywood Movie About Trapped Miners Released ...       0   1.0   
2335  @mickinyman @TheAtlantic That or they might be...       0   1.0   
5859  .POTUS #StrategicPatience is a strategy for #G...       0   1.0   
1879  FWD: I literally jumped out of bed put on beac...       0   1.0   
216   Video Captures Man Removing American Flag From...       0   1.0   
243   @adorableappple No reported flooding po in the...       0   1.0   
5890  Teen Disaster Preparedness Event in Van Nuys A...       0   1.0   
4648  wowo--=== 12000 Nigerian refugees repatriated ...       0   1.0   
4653  #hot  C-130 specially modified to land in a st...       0   1.0   
5582  Kosciusko police investigating pedestrian fata...       0   1.0   

          prob  
4517  0.770442  
2335  0.781370  
5859  0.783202  
1879  0.784837  
216   0.802437  
243   0.803092  
5890  0.821565  
4648  0.827007  
4653  0.938754  
5582  0.994299

### 5 most wrong disaster tweets:


In [98]:
for i in np.arange(0,5):
  print(worst_preds.iloc[i,0],'\n')
  print(f'target: {worst_preds.iloc[i,1]}, prediction: {worst_preds.iloc[i,2]}, prob: {worst_preds.iloc[i,3]} \n')
  print('========================')

The media needs to stop publicizing mass murder. So many sick people do these things for the eyes of the world &amp; the media is not helping. 

target: 1, prediction: 0.0, prob: 0.005086719989776611 

OH MY GOD RYANS IN TROUBLE http://t.co/ADIp0UnXHU 

target: 1, prediction: 0.0, prob: 0.009995579719543457 

Omg if Cain dies i will be an emotional wreck #emmerdale 

target: 1, prediction: 0.0, prob: 0.02365279197692871 

‰ÛÏ@LordBrathwaite: Everyone Here: Ahh I hate snow!

Me: Lol u call this a snowstorm..?

#growingupincolorado‰Û 

target: 1, prediction: 0.0, prob: 0.03077659010887146 

#Nursing alert: Emergency Department Psychiatric RN (.90 FTE Day) | Providence Health &amp; Services | #Olympia WA http://t.co/Yu6NUe7gFB 

target: 1, prediction: 0.0, prob: 0.03158724308013916 



### 5 most wrong Non-disaster tweets:


In [99]:
for i in np.arange(1,6)*-1:
  print(worst_preds.iloc[i,0],'\n')
  print(f'target: {worst_preds.iloc[i,1]}, prediction: {worst_preds.iloc[i,2]}, prob: {worst_preds.iloc[i,3]} \n')
  print('========================')

Kosciusko police investigating pedestrian fatality hit by a train Thursday http://t.co/m5djLLxoZP 

target: 0, prediction: 1.0, prob: 0.9942992329597473 

#hot  C-130 specially modified to land in a stadium and rescue hostages in Iran in 1980 http://t.co/zY3hpdJNwg #prebreak #best 

target: 0, prediction: 1.0, prob: 0.9387543201446533 

wowo--=== 12000 Nigerian refugees repatriated from Cameroon 

target: 0, prediction: 1.0, prob: 0.8270071148872375 

Teen Disaster Preparedness Event in Van Nuys August 11 @ 5:30pm http://t.co/fXUX987vZx via @VanNuysCouncil 

target: 0, prediction: 1.0, prob: 0.8215647339820862 

@adorableappple No reported flooding po in the area. Ten-4. #mmda 

target: 0, prediction: 1.0, prob: 0.8030920624732971 

